//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests
    {
        public int IdTest { get; set; }
        public string TestName { get; set; }
        public string TaskOption { get; set; }
        public string NumberQuestions { get; set; }
        public string CorrectAnswers { get; set; }
        public string NumberPoints { get; set; }
        public string Evaluation { get; set; }
        public int IdUser { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
